//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogar_Dulce_Corazón____Juan_Palacios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoptive_Parents
    {
        public int ID_AdoptiveParents { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Cellphone { get; set; }
        public string Work_Address { get; set; }
        public Nullable<int> ID_Genre { get; set; }
        public Nullable<int> ID_MedicalHistory { get; set; }
        public Nullable<int> ID_AdoptionDetail { get; set; }
    
        public virtual Adoption_Detail Adoption_Detail { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Medical_History Medical_History { get; set; }
    }
}
