//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogar_Dulce_Corazón____Juan_Palacios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoption_Detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adoption_Detail()
        {
            this.Adoptive_Parents = new HashSet<Adoptive_Parents>();
        }
    
        public int ID_AdoptionDetail { get; set; }
        public System.DateTime Moving_Date { get; set; }
        public System.DateTime Adoption_Date { get; set; }
        public System.DateTime Return_Date { get; set; }
        public Nullable<int> ID_Children { get; set; }
    
        public virtual Children Children { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoptive_Parents> Adoptive_Parents { get; set; }
    }
}
