//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogar_Dulce_Corazón____Juan_Palacios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_History
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medical_History()
        {
            this.Adoptive_Parents = new HashSet<Adoptive_Parents>();
        }
    
        public int ID_MedicalHistory { get; set; }
        public Nullable<int> ID_Children { get; set; }
        public string Description { get; set; }
        public Nullable<int> ID_Illeness { get; set; }
        public string Treatment { get; set; }
        public System.DateTime Evaluation_Date { get; set; }
        public Nullable<int> ID_BloodType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoptive_Parents> Adoptive_Parents { get; set; }
        public virtual Blood_Type Blood_Type { get; set; }
        public virtual Children Children { get; set; }
        public virtual Illness Illness { get; set; }
    }
}
