//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogar_Dulce_Corazón____Juan_Palacios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DulceCorazonEntities : DbContext
    {
        public DulceCorazonEntities()
            : base("name=DulceCorazonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adoption_Detail> Adoption_Detail { get; set; }
        public virtual DbSet<Adoptive_Parents> Adoptive_Parents { get; set; }
        public virtual DbSet<Blood_Type> Blood_Type { get; set; }
        public virtual DbSet<Children> Children { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Illness> Illness { get; set; }
        public virtual DbSet<Medical_History> Medical_History { get; set; }
        public virtual DbSet<Temporal_Place> Temporal_Place { get; set; }
        public virtual DbSet<Temporary_Caregiver> Temporary_Caregiver { get; set; }
    }
}
