//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hogar_Dulce_Corazón____Juan_Palacios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporal_Place
    {
        public int ID_TemporalPlace { get; set; }
        public string Address { get; set; }
        public string Cellphone { get; set; }
        public Nullable<int> ID_Children { get; set; }
        public Nullable<int> ID_TemporaryCaregiver { get; set; }
    
        public virtual Children Children { get; set; }
        public virtual Temporary_Caregiver Temporary_Caregiver { get; set; }
    }
}
